#!/bin/bash

# Download Canadian Regulations (SOR/DORS) Data
# This script provides instructions for downloading regulation XML files

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="$SCRIPT_DIR/../data/regulations/canadian_laws"

echo "========================================="
echo "Canadian Regulations Download Script"
echo "========================================="
echo ""
echo "This script sets up directories for regulations data."
echo "You must manually download the regulation XML files."
echo ""

# Create directories
mkdir -p "$DATA_DIR/en-regs"
mkdir -p "$DATA_DIR/fr-regs"

echo "✓ Created directories:"
echo "  - $DATA_DIR/en-regs/ (English regulations)"
echo "  - $DATA_DIR/fr-regs/ (French regulations)"
echo ""

echo "========================================="
echo "DOWNLOAD INSTRUCTIONS"
echo "========================================="
echo ""
echo "Option 1: Download from Justice Laws Website"
echo "---------------------------------------------"
echo "1. Visit: https://laws-lois.justice.gc.ca/eng/regulations/"
echo ""
echo "2. You can download individual regulations:"
echo "   - Search for regulation by name or SOR number"
echo "   - Click on regulation"
echo "   - Click 'XML' button to download"
echo "   - Save to: $DATA_DIR/en-regs/"
echo ""
echo "3. For bulk download, contact:"
echo "   Email: laws-lois@justice.gc.ca"
echo "   Subject: Request for bulk SOR/DORS XML download"
echo ""

echo "Option 2: Download from Open Canada Portal"
echo "-------------------------------------------"
echo "1. Visit: https://open.canada.ca/data/en/dataset/1f0aae37-18e4-4bad-bbca-59a4094e44fa"
echo ""
echo "2. Look for 'Consolidated Federal Regulations' dataset"
echo "   Note: May require separate download from Acts"
echo ""
echo "3. Extract regulation XML files to:"
echo "   English: $DATA_DIR/en-regs/"
echo "   French:  $DATA_DIR/fr-regs/"
echo ""

echo "========================================="
echo "PRIORITY REGULATIONS (For Testing)"
echo "========================================="
echo ""
echo "Download these high-priority regulations first:"
echo ""
echo "1. SOR/96-445  - Employment Insurance Regulations"
echo "2. SOR/2002-227 - Immigration and Refugee Protection Regulations"
echo "3. SOR/2018-144 - Cannabis Regulations"
echo "4. SOR/78-859  - Canada Pension Plan Regulations"
echo "5. SOR/96-521  - Old Age Security Regulations"
echo ""

echo "========================================="
echo "AFTER DOWNLOADING"
echo "========================================="
echo ""
echo "Once you have regulations XML files in the directories:"
echo ""
echo "1. Verify files are present:"
echo "   ls -la $DATA_DIR/en-regs/"
echo ""
echo "2. Run ingestion pipeline:"
echo "   docker compose exec backend python ingestion/data_pipeline.py --xml-dir data/regulations/canadian_laws"
echo ""
echo "3. Rebuild knowledge graph:"
echo "   docker compose exec backend python tasks/populate_graph.py --clear"
echo ""

echo "========================================="
echo "Setup complete! Follow instructions above to download regulations."
echo "========================================="
