"""sync models with database as of 2025-12-21

Revision ID: 03d196580ff8
Revises: g2h4j5k6m7n8
Create Date: 2025-12-21 06:44:29.053968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03d196580ff8'
down_revision = 'g2h4j5k6m7n8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_metadata_doc_key', 'document_metadata', ['document_id', 'key'], unique=False)
    op.alter_column('alert_subscriptions', 'jurisdiction',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_alert_subscriptions_active', table_name='alert_subscriptions')
    op.drop_index('idx_alert_subscriptions_jurisdiction', table_name='alert_subscriptions')
    op.drop_index('idx_alert_subscriptions_user', table_name='alert_subscriptions')
    op.drop_constraint('alert_subscriptions_user_id_fkey', 'alert_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'alert_subscriptions', 'users', ['user_id'], ['id'])
    op.alter_column('alerts', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('alerts', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_index('idx_alerts_subscription_read_date', table_name='alerts')
    op.drop_constraint('alerts_regulation_id_fkey', 'alerts', type_='foreignkey')
    op.drop_constraint('alerts_subscription_id_fkey', 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'regulations', ['regulation_id'], ['id'])
    op.create_foreign_key(None, 'alerts', 'alert_subscriptions', ['subscription_id'], ['id'])
    op.drop_column('alerts', 'metadata')
    op.alter_column('amendments', 'effective_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('amendments', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('amendments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_amendments_effective_date', table_name='amendments')
    op.drop_index('idx_amendments_regulation', table_name='amendments')
    op.drop_constraint('amendments_regulation_id_fkey', 'amendments', type_='foreignkey')
    op.create_foreign_key(None, 'amendments', 'regulations', ['regulation_id'], ['id'])
    op.drop_column('amendments', 'metadata')
    op.alter_column('citations', 'cited_section_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('citations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_citations_cited', table_name='citations')
    op.drop_index('idx_citations_section', table_name='citations')
    op.drop_constraint('citations_section_id_fkey', 'citations', type_='foreignkey')
    op.drop_constraint('citations_cited_section_id_fkey', 'citations', type_='foreignkey')
    op.create_foreign_key(None, 'citations', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'citations', 'sections', ['cited_section_id'], ['id'])
    op.add_column('cross_references', sa.Column('document_id', sa.UUID(), nullable=False))
    op.add_column('cross_references', sa.Column('source_section', sa.String(length=100), nullable=True))
    op.add_column('cross_references', sa.Column('source_text', sa.Text(), nullable=True))
    op.add_column('cross_references', sa.Column('target_document', sa.String(length=500), nullable=True))
    op.add_column('cross_references', sa.Column('target_section', sa.String(length=100), nullable=True))
    op.add_column('cross_references', sa.Column('reference_metadata', sa.JSON(), nullable=True))
    op.alter_column('cross_references', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_cross_references_source_doc', table_name='cross_references')
    op.drop_index('idx_cross_references_target_doc', table_name='cross_references')
    op.drop_index('idx_cross_references_type', table_name='cross_references')
    op.drop_constraint('cross_references_source_section_id_fkey', 'cross_references', type_='foreignkey')
    op.drop_constraint('cross_references_target_document_id_fkey', 'cross_references', type_='foreignkey')
    op.drop_constraint('cross_references_target_section_id_fkey', 'cross_references', type_='foreignkey')
    op.drop_constraint('cross_references_source_document_id_fkey', 'cross_references', type_='foreignkey')
    op.create_foreign_key(None, 'cross_references', 'documents', ['document_id'], ['id'])
    op.drop_column('cross_references', 'source_location')
    op.drop_column('cross_references', 'target_section_id')
    op.drop_column('cross_references', 'context')
    op.drop_column('cross_references', 'source_section_id')
    op.drop_column('cross_references', 'citation_text')
    op.drop_column('cross_references', 'source_document_id')
    op.drop_column('cross_references', 'target_location')
    op.add_column('document_clauses', sa.Column('section_id', sa.UUID(), nullable=False))
    op.add_column('document_clauses', sa.Column('clause_number', sa.String(length=50), nullable=True))
    op.add_column('document_clauses', sa.Column('clause_type', sa.String(length=50), nullable=True))
    op.add_column('document_clauses', sa.Column('clause_metadata', sa.JSON(), nullable=True))
    op.alter_column('document_clauses', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('document_clauses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_document_clauses_order', table_name='document_clauses')
    op.drop_index('idx_document_clauses_subsection', table_name='document_clauses')
    op.drop_constraint('document_clauses_subsection_id_fkey', 'document_clauses', type_='foreignkey')
    op.create_foreign_key(None, 'document_clauses', 'document_sections', ['section_id'], ['id'])
    op.drop_column('document_clauses', 'clause_identifier')
    op.drop_column('document_clauses', 'updated_at')
    op.drop_column('document_clauses', 'subsection_id')
    op.add_column('document_sections', sa.Column('section_metadata', sa.JSON(), nullable=True))
    op.alter_column('document_sections', 'section_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('document_sections', 'section_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('document_sections', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('document_sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('document_sections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_document_sections_document', table_name='document_sections')
    op.drop_index('idx_document_sections_number', table_name='document_sections')
    op.drop_index('idx_document_sections_order', table_name='document_sections')
    op.drop_index('idx_document_sections_parent', table_name='document_sections')
    op.create_index('ix_document_sections_doc_number', 'document_sections', ['document_id', 'section_number'], unique=False)
    op.drop_constraint('document_sections_parent_section_id_fkey', 'document_sections', type_='foreignkey')
    op.drop_constraint('document_sections_document_id_fkey', 'document_sections', type_='foreignkey')
    op.create_foreign_key(None, 'document_sections', 'document_sections', ['parent_section_id'], ['id'])
    op.create_foreign_key(None, 'document_sections', 'documents', ['document_id'], ['id'])
    op.add_column('document_subsections', sa.Column('subsection_title', sa.String(length=500), nullable=True))
    op.add_column('document_subsections', sa.Column('subsection_metadata', sa.JSON(), nullable=True))
    op.alter_column('document_subsections', 'subsection_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('document_subsections', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('document_subsections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('document_subsections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_document_subsections_order', table_name='document_subsections')
    op.drop_index('idx_document_subsections_section', table_name='document_subsections')
    op.drop_constraint('document_subsections_section_id_fkey', 'document_subsections', type_='foreignkey')
    op.create_foreign_key(None, 'document_subsections', 'document_sections', ['section_id'], ['id'])
    op.drop_column('document_subsections', 'level')
    op.add_column('documents', sa.Column('doc_metadata', sa.JSON(), nullable=True))
    op.alter_column('documents', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('documents', 'authority',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'file_format',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'effective_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'publication_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_documents_jurisdiction', table_name='documents')
    op.drop_index('idx_documents_processed', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_title_search', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_type', table_name='documents')
    op.create_index(op.f('ix_documents_jurisdiction'), 'documents', ['jurisdiction'], unique=False)
    op.create_index('ix_documents_type_jurisdiction', 'documents', ['document_type', 'jurisdiction'], unique=False)
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'processed_date')
    op.alter_column('query_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('query_history', 'entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('query_history', 'intent',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('query_history', 'results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('query_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_query_history_created_at', table_name='query_history')
    op.drop_index('idx_query_history_intent', table_name='query_history')
    op.drop_index('idx_query_history_user_date', table_name='query_history')
    op.drop_constraint('query_history_user_id_fkey', 'query_history', type_='foreignkey')
    op.create_foreign_key(None, 'query_history', 'users', ['user_id'], ['id'])
    op.alter_column('regulations', 'jurisdiction',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('regulations', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('regulations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('regulations', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('regulations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('regulations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_regulations_effective_date', table_name='regulations')
    op.drop_index('idx_regulations_jurisdiction', table_name='regulations')
    op.drop_index('idx_regulations_status', table_name='regulations')
    op.drop_index('idx_regulations_title_search', table_name='regulations', postgresql_using='gin')
    op.drop_index('ix_regulations_search_vector', table_name='regulations', postgresql_using='gin')
    op.drop_index('ix_regulations_search_vector_fr', table_name='regulations', postgresql_using='gin')
    op.create_index(op.f('ix_regulations_content_hash'), 'regulations', ['content_hash'], unique=False)
    op.create_index(op.f('ix_regulations_jurisdiction'), 'regulations', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_regulations_status'), 'regulations', ['status'], unique=False)
    op.create_index(op.f('ix_regulations_title'), 'regulations', ['title'], unique=False)
    op.create_index('ix_regulations_title_jurisdiction', 'regulations', ['title', 'jurisdiction'], unique=False)
    op.drop_column('regulations', 'metadata')
    op.alter_column('sections', 'section_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sections', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sections', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('sections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_sections_content_search', table_name='sections', postgresql_using='gin')
    op.drop_index('idx_sections_number', table_name='sections')
    op.drop_index('idx_sections_regulation', table_name='sections')
    op.drop_index('ix_sections_search_vector', table_name='sections', postgresql_using='gin')
    op.drop_index('ix_sections_search_vector_fr', table_name='sections', postgresql_using='gin')
    op.create_index('ix_sections_regulation_number', 'sections', ['regulation_id', 'section_number'], unique=False)
    op.create_unique_constraint('uq_section_regulation', 'sections', ['regulation_id', 'section_number'])
    op.drop_constraint('sections_regulation_id_fkey', 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'regulations', ['regulation_id'], ['id'])
    op.drop_column('sections', 'metadata')
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_users_department', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('workflow_sessions', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_workflow_sessions_started_at', table_name='workflow_sessions')
    op.drop_index('idx_workflow_sessions_status', table_name='workflow_sessions')
    op.drop_index('idx_workflow_sessions_user_date', table_name='workflow_sessions')
    op.drop_constraint('workflow_sessions_user_id_fkey', 'workflow_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('workflow_sessions', 'metadata')
    op.alter_column('workflow_steps', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('workflow_steps', 'validation_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('workflow_steps', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_workflow_steps_session', table_name='workflow_steps')
    op.drop_constraint('workflow_steps_session_id_fkey', 'workflow_steps', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_steps', 'workflow_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.create_foreign_key('workflow_steps_session_id_fkey', 'workflow_steps', 'workflow_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_workflow_steps_session', 'workflow_steps', ['session_id', 'step_number'], unique=False)
    op.alter_column('workflow_steps', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('workflow_steps', 'validation_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_steps', 'input_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('workflow_sessions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflow_sessions', type_='foreignkey')
    op.create_foreign_key('workflow_sessions_user_id_fkey', 'workflow_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_workflow_sessions_user_date', 'workflow_sessions', ['user_id', sa.text('started_at DESC')], unique=False)
    op.create_index('idx_workflow_sessions_status', 'workflow_sessions', ['status'], unique=False)
    op.create_index('idx_workflow_sessions_started_at', 'workflow_sessions', ['started_at'], unique=False)
    op.alter_column('workflow_sessions', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'started_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'status',
               existing_type=sa.String(length=50),
               server_default=sa.text("'active'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('workflow_sessions', 'state',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_department', 'users', ['department'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('sections', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key('sections_regulation_id_fkey', 'sections', 'regulations', ['regulation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_section_regulation', 'sections', type_='unique')
    op.drop_index('ix_sections_regulation_number', table_name='sections')
    op.create_index('ix_sections_search_vector_fr', 'sections', ['search_vector_fr'], unique=False, postgresql_using='gin')
    op.create_index('ix_sections_search_vector', 'sections', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_sections_regulation', 'sections', ['regulation_id'], unique=False)
    op.create_index('idx_sections_number', 'sections', ['section_number'], unique=False)
    op.create_index('idx_sections_content_search', 'sections', ['content'], unique=False, postgresql_using='gin')
    op.alter_column('sections', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sections', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sections', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('sections', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sections', 'section_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('regulations', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index('ix_regulations_title_jurisdiction', table_name='regulations')
    op.drop_index(op.f('ix_regulations_title'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_status'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_jurisdiction'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_content_hash'), table_name='regulations')
    op.create_index('ix_regulations_search_vector_fr', 'regulations', ['search_vector_fr'], unique=False, postgresql_using='gin')
    op.create_index('ix_regulations_search_vector', 'regulations', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_regulations_title_search', 'regulations', ['title'], unique=False, postgresql_using='gin')
    op.create_index('idx_regulations_status', 'regulations', ['status'], unique=False)
    op.create_index('idx_regulations_jurisdiction', 'regulations', ['jurisdiction'], unique=False)
    op.create_index('idx_regulations_effective_date', 'regulations', [sa.text('effective_date DESC')], unique=False)
    op.alter_column('regulations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('regulations', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('regulations', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('regulations', 'status',
               existing_type=sa.String(length=50),
               server_default=sa.text("'active'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('regulations', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.alter_column('regulations', 'jurisdiction',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'query_history', type_='foreignkey')
    op.create_foreign_key('query_history_user_id_fkey', 'query_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_query_history_user_date', 'query_history', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_query_history_intent', 'query_history', ['intent'], unique=False)
    op.create_index('idx_query_history_created_at', 'query_history', ['created_at'], unique=False)
    op.alter_column('query_history', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('query_history', 'results',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('query_history', 'intent',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('query_history', 'entities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('query_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('documents', sa.Column('processed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('ix_documents_type_jurisdiction', table_name='documents')
    op.drop_index(op.f('ix_documents_jurisdiction'), table_name='documents')
    op.create_index('idx_documents_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_documents_title_search', 'documents', ['title'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_processed', 'documents', ['is_processed'], unique=False)
    op.create_index('idx_documents_jurisdiction', 'documents', ['jurisdiction'], unique=False)
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'upload_date',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'publication_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'effective_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'file_format',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('documents', 'authority',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('documents', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('documents', 'doc_metadata')
    op.add_column('document_subsections', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_subsections', type_='foreignkey')
    op.create_foreign_key('document_subsections_section_id_fkey', 'document_subsections', 'document_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_document_subsections_section', 'document_subsections', ['section_id'], unique=False)
    op.create_index('idx_document_subsections_order', 'document_subsections', ['section_id', 'order_index'], unique=False)
    op.alter_column('document_subsections', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_subsections', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_subsections', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('document_subsections', 'subsection_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('document_subsections', 'subsection_metadata')
    op.drop_column('document_subsections', 'subsection_title')
    op.drop_constraint(None, 'document_sections', type_='foreignkey')
    op.drop_constraint(None, 'document_sections', type_='foreignkey')
    op.create_foreign_key('document_sections_document_id_fkey', 'document_sections', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('document_sections_parent_section_id_fkey', 'document_sections', 'document_sections', ['parent_section_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_document_sections_doc_number', table_name='document_sections')
    op.create_index('idx_document_sections_parent', 'document_sections', ['parent_section_id'], unique=False)
    op.create_index('idx_document_sections_order', 'document_sections', ['document_id', 'order_index'], unique=False)
    op.create_index('idx_document_sections_number', 'document_sections', ['section_number'], unique=False)
    op.create_index('idx_document_sections_document', 'document_sections', ['document_id'], unique=False)
    op.alter_column('document_sections', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_sections', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_sections', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('document_sections', 'section_title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('document_sections', 'section_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('document_sections', 'section_metadata')
    op.add_column('document_clauses', sa.Column('subsection_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('document_clauses', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_clauses', sa.Column('clause_identifier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_clauses', type_='foreignkey')
    op.create_foreign_key('document_clauses_subsection_id_fkey', 'document_clauses', 'document_subsections', ['subsection_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_document_clauses_subsection', 'document_clauses', ['subsection_id'], unique=False)
    op.create_index('idx_document_clauses_order', 'document_clauses', ['subsection_id', 'order_index'], unique=False)
    op.alter_column('document_clauses', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_clauses', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('document_clauses', 'clause_metadata')
    op.drop_column('document_clauses', 'clause_type')
    op.drop_column('document_clauses', 'clause_number')
    op.drop_column('document_clauses', 'section_id')
    op.add_column('cross_references', sa.Column('target_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cross_references', sa.Column('source_document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('cross_references', sa.Column('citation_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cross_references', sa.Column('source_section_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('cross_references', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cross_references', sa.Column('target_section_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('cross_references', sa.Column('source_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cross_references', type_='foreignkey')
    op.create_foreign_key('cross_references_source_document_id_fkey', 'cross_references', 'documents', ['source_document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cross_references_target_section_id_fkey', 'cross_references', 'document_sections', ['target_section_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('cross_references_target_document_id_fkey', 'cross_references', 'documents', ['target_document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('cross_references_source_section_id_fkey', 'cross_references', 'document_sections', ['source_section_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_cross_references_type', 'cross_references', ['reference_type'], unique=False)
    op.create_index('idx_cross_references_target_doc', 'cross_references', ['target_document_id'], unique=False)
    op.create_index('idx_cross_references_source_doc', 'cross_references', ['source_document_id'], unique=False)
    op.alter_column('cross_references', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('cross_references', 'reference_metadata')
    op.drop_column('cross_references', 'target_section')
    op.drop_column('cross_references', 'target_document')
    op.drop_column('cross_references', 'source_text')
    op.drop_column('cross_references', 'source_section')
    op.drop_column('cross_references', 'document_id')
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.create_foreign_key('citations_cited_section_id_fkey', 'citations', 'sections', ['cited_section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('citations_section_id_fkey', 'citations', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_citations_section', 'citations', ['section_id'], unique=False)
    op.create_index('idx_citations_cited', 'citations', ['cited_section_id'], unique=False)
    op.alter_column('citations', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('citations', 'cited_section_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('amendments', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'amendments', type_='foreignkey')
    op.create_foreign_key('amendments_regulation_id_fkey', 'amendments', 'regulations', ['regulation_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_amendments_regulation', 'amendments', ['regulation_id'], unique=False)
    op.create_index('idx_amendments_effective_date', 'amendments', [sa.text('effective_date DESC')], unique=False)
    op.alter_column('amendments', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('amendments', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('amendments', 'effective_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('alerts', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key('alerts_subscription_id_fkey', 'alerts', 'alert_subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('alerts_regulation_id_fkey', 'alerts', 'regulations', ['regulation_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_alerts_subscription_read_date', 'alerts', ['subscription_id', 'read', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('alerts', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('alerts', 'read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('alerts', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'alert_subscriptions', type_='foreignkey')
    op.create_foreign_key('alert_subscriptions_user_id_fkey', 'alert_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_alert_subscriptions_user', 'alert_subscriptions', ['user_id'], unique=False)
    op.create_index('idx_alert_subscriptions_jurisdiction', 'alert_subscriptions', ['jurisdiction'], unique=False)
    op.create_index('idx_alert_subscriptions_active', 'alert_subscriptions', ['active'], unique=False)
    op.alter_column('alert_subscriptions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'frequency',
               existing_type=sa.String(length=50),
               server_default=sa.text("'daily'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'topics',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('alert_subscriptions', 'jurisdiction',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index('ix_document_metadata_doc_key', table_name='document_metadata')
    op.drop_table('document_metadata')
    # ### end Alembic commands ###
