"""removing document models

Revision ID: b55b4b527f0e
Revises: ccab933c8e27
Create Date: 2025-12-24 15:59:40.408457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b55b4b527f0e'
down_revision = 'ccab933c8e27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first to avoid dependency issues
    op.drop_constraint('document_subsections_section_id_fkey', 'document_subsections', type_='foreignkey')
    op.drop_constraint('document_clauses_section_id_fkey', 'document_clauses', type_='foreignkey')
    op.drop_constraint('document_sections_document_id_fkey', 'document_sections', type_='foreignkey')
    op.drop_constraint('document_sections_parent_section_id_fkey', 'document_sections', type_='foreignkey')
    op.drop_constraint('cross_references_document_id_fkey', 'cross_references', type_='foreignkey')
    op.drop_constraint('document_metadata_document_id_fkey', 'document_metadata', type_='foreignkey')
    
    # Now drop tables in safe order
    # 1. Tables with FK to document_sections
    op.drop_table('document_subsections')
    op.drop_table('document_clauses')
    
    # 2. Tables with FK to documents
    op.drop_index('ix_document_sections_doc_number', table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_table('cross_references')
    op.drop_index('ix_document_metadata_doc_key', table_name='document_metadata')
    op.drop_table('document_metadata')
    
    # 3. Finally drop documents table (no more dependencies)
    op.drop_index('ix_documents_file_hash', table_name='documents')
    op.drop_index('ix_documents_jurisdiction', table_name='documents')
    op.drop_index('ix_documents_title', table_name='documents')
    op.drop_index('ix_documents_type_jurisdiction', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_section_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('section_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('section_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('section_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_sections_document_id_fkey'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['document_sections.id'], name='document_sections_parent_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_sections_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_document_sections_doc_number', 'document_sections', ['document_id', 'section_number'], unique=False)
    op.create_table('document_metadata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_metadata_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_metadata_pkey')
    )
    op.create_index('ix_document_metadata_doc_key', 'document_metadata', ['document_id', 'key'], unique=False)
    op.create_table('cross_references',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_section', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_document', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('target_section', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reference_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='cross_references_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cross_references_pkey')
    )
    op.create_table('document_clauses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clause_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('clause_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('clause_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name='document_clauses_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_clauses_pkey')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('LEGISLATION', 'REGULATION', 'POLICY', 'GUIDELINE', 'DIRECTIVE', 'ORDER', 'BYLAW', 'OTHER', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('document_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('jurisdiction', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('authority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('effective_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'AMENDED', 'REPEALED', 'ARCHIVED', name='documentstatus'), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('doc_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='documents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_documents_type_jurisdiction', 'documents', ['document_type', 'jurisdiction'], unique=False)
    op.create_index('ix_documents_title', 'documents', ['title'], unique=False)
    op.create_index('ix_documents_jurisdiction', 'documents', ['jurisdiction'], unique=False)
    op.create_index('ix_documents_file_hash', 'documents', ['file_hash'], unique=True)
    op.create_table('document_subsections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subsection_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subsection_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('subsection_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name='document_subsections_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_subsections_pkey')
    )
    # ### end Alembic commands ###
